FROM rust:1.91-slim-bookworm AS builder
WORKDIR /app

RUN apt-get update && apt-get install -y pkg-config libssl-dev && rm -rf /var/lib/apt/lists/*

COPY vox-connections /vox-connections
COPY Cargo.toml Cargo.lock ./
COPY build.rs ./
COPY migrations ./migrations
COPY contracts ./contracts
COPY defaults ./defaults
COPY services ./services
COPY src ./src

RUN cargo build --release --locked --bin vox-core-worker

FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y ca-certificates curl && rm -rf /var/lib/apt/lists/*

RUN useradd -m -u 1000 -U vox
USER vox

COPY --from=builder --chown=vox:vox /app/target/release/vox-core-worker /usr/local/bin/vox-core-worker

CMD ["/usr/local/bin/vox-core-worker"]
