UPDATE agent_capability_grants SET state='revoked',revoked_at=now(),updated_at=now();
UPDATE external_connections SET authorization_state='revoked',revoked_at=now(),updated_at=now(),expires_at=NULL;
UPDATE action_proposals SET state='expired' WHERE state IN ('pending','approved') AND id IN (SELECT proposal_id FROM action_approvals WHERE consumed_execution_id IS NULL);
DROP TABLE IF EXISTS connector_setups;
DROP TABLE IF EXISTS connector_package_installations;
DROP TABLE IF EXISTS connector_packages;
DROP TRIGGER IF EXISTS connector_tool_metadata_index ON remote_extension_versions;
DROP FUNCTION IF EXISTS index_connector_tool_metadata();
DROP TABLE IF EXISTS connector_tool_metadata;
DROP TABLE IF EXISTS connector_skill_installations;
DROP TABLE IF EXISTS connected_app_pending_actions;
DROP TABLE IF EXISTS mcp_authorization_sessions;
DROP TABLE IF EXISTS mcp_oauth_clients;
DROP TABLE IF EXISTS remote_extension_credentials;
DROP TABLE IF EXISTS playstation_accounts;
ALTER TABLE agent_capability_grants RENAME TO retired_agent_capability_grants;
ALTER TABLE external_connections RENAME TO retired_external_connections;
ALTER TABLE integration_definitions RENAME TO retired_integration_definitions;
ALTER TABLE remote_extension_conformance_runs RENAME TO retired_remote_extension_conformance_runs;
ALTER TABLE remote_extension_versions RENAME TO retired_remote_extension_versions;
ALTER TABLE remote_extensions RENAME TO retired_remote_extensions;
